ENTRYINIT-T-8 Home UI
EntryDSM/Persian pull request #2
Opened 2021-03-18 07:15 UTC by woochanleee

#  ENTRYINIT-T-8 Home UI 마크업

## 목적

홈 UI 마크업 및 가로 스크롤뷰 스타일링 관련 리뷰를 받기 위해

### 요약

홈 UI 마크업 하였습니다.

### 상세
pages/index.tsx, components/content/content-list/index.tsx 봐주시면 될것 같습니다.

## 영향을 미치는 부분

X

## 참조(선택)

- 같은 고민을 하는 듯한 이슈 https://stackoverflow.com/questions/11695354/css-right-margin-does-not-work-inside-a-div-with-overflow-scroll

2021-03-20 18:17 UTC, engolder requested changes

2021-03-20 18:17 UTC, engolder commented on web-app/components/navigation-bar/index.tsx
> +      </S.ButtonWrapper>
```suggestion
      <S.NavLink
        as={Link}
        key={link}
        aria-current={pathname === link ? "page" : "false"}
        href={link}
      >
        {text}
      </S.NavLink>
```
이렇게 해놓고 NavLink에서
```scss
["aria-current"="page"] {
  background-color: #c7c7f9;
}
```
하면 ARIA 준수 ^^

2021-03-20 18:17 UTC, engolder commented on web-app/components/banner/index.tsx
> +import Slider from 'react-slick';
https://www.npmjs.com/package/keen-slider
추천합니다

2021-03-20 18:17 UTC, engolder commented on web-app/components/skeleton-ui/Skeleton.tsx
> +  }
```suggestion
  0% {
    background-position-x: -90px;
  }
  100% {
    background-position-x: ${width} + 90px;
  }
```

2021-03-20 18:17 UTC, engolder commented on web-app/components/skeleton-ui/Skeleton.tsx
> +            animation: ${getSkeletonAnimation(width)} 2s infinite ease-out;
그리고 여기에 지연시간좀 넣으면 될듯

2021-03-22 08:08 UTC, khg0712 commented on web-app/pages/_app.tsx
> +            height: calc(100vh - 50px);
하나 지워야 할듯요

2021-03-22 12:45 UTC, woochanleee commented on web-app/pages/_app.tsx
> +            height: calc(100vh - 50px);
감사합니다!

2021-03-25 04:04 UTC, merged